import 'dotenv/config';
import express from 'express';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { randomUUID } from 'node:crypto';
import { listAccounts, getAccount, saveAccount, deleteAccount, listConversations, listEntities, getEntity, upsertEntity, deleteEntity, appendAudit, listAudit } from './store.mjs';
import { saveBinaryFile, readBinaryFile, deleteBinaryFile, MAX_BYTES } from './files.mjs';
import { catalogModels, complete, completeMany, listModels, testConnection } from './providers.mjs';
const __dirname=path.dirname(fileURLToPath(import.meta.url)); const app=express(); const port=Number(process.env.PORT||3001); app.use(express.json({limit:'35mb'}));
app.get('/api/health',(_req,res)=>res.json({ok:true,service:'ai-nexus',version:'0.6.0',time:new Date().toISOString()}));
app.get('/api/models',(_req,res)=>res.json({models:catalogModels()}));
app.get('/api/accounts',async(_req,res)=>res.json({accounts:await listAccounts()}));
app.post('/api/accounts',async(req,res)=>{try{return res.status(201).json({account:await saveAccount(req.body)})}catch(e){return res.status(400).json({error:e.message})}});
app.delete('/api/accounts/:id',async(req,res)=>res.json({deleted:await deleteAccount(req.params.id)}));
app.get('/api/accounts/:id/models',async(req,res)=>{try{const a=await getAccount(req.params.id);if(!a)return res.status(404).json({error:'Account not found.'});return res.json({models:await listModels({providerId:a.providerId,apiKey:a.secret,baseUrl:a.baseUrl})})}catch(e){return res.status(502).json({error:e.message})}});
app.post('/api/accounts/:id/test',async(req,res)=>{try{const a=await getAccount(req.params.id);if(!a)return res.status(404).json({error:'Account not found.'});return res.json(await testConnection({providerId:a.providerId,apiKey:a.secret,baseUrl:a.baseUrl}))}catch(e){return res.status(502).json({ok:false,error:e.message})}});
app.get('/api/conversations',async(_req,res)=>res.json({conversations:await listConversations()}));
app.post('/api/conversations',async(req,res)=>{try{return res.status(201).json({conversation:await upsertEntity('conversations',req.body)})}catch(e){return res.status(400).json({error:e.message})}});
app.get('/api/conversations/:id',async(req,res)=>{const c=await getEntity('conversations',req.params.id);if(!c)return res.status(404).json({error:'Conversation not found.'});return res.json({conversation:c})});
app.put('/api/conversations/:id',async(req,res)=>res.json({conversation:await upsertEntity('conversations',{...req.body,id:req.params.id})}));
app.delete('/api/conversations/:id',async(req,res)=>res.json({deleted:await deleteEntity('conversations',req.params.id)}));
function publicFile(meta){if(!meta)return null;const {storagePath:_storagePath,...safe}=meta;return safe;}
app.get('/api/files',async(_req,res)=>{const files=await listEntities('files');res.json({files:files.map(publicFile)});});
app.get('/api/files/limits',(_req,res)=>res.json({maxBytes:MAX_BYTES,maxMegabytes:MAX_BYTES/1024/1024}));
app.get('/api/files/:id',async(req,res)=>{const f=await getEntity('files',req.params.id);if(!f)return res.status(404).json({error:'File not found.'});res.json({file:publicFile(f)});});
app.post('/api/files/upload',async(req,res)=>{try{const meta=await saveBinaryFile(req.body||{});const file=await upsertEntity('files',meta);await appendAudit('file_uploaded',file.id,{name:file.originalName,size:file.size},'info');return res.status(201).json({file:publicFile(file)})}catch(e){return res.status(400).json({error:e.message})}});
app.get('/api/files/:id/content',async(req,res)=>{try{const f=await getEntity('files',req.params.id);if(!f)return res.status(404).json({error:'File not found.'});const data=await readBinaryFile(f);res.setHeader('Content-Type',f.mimeType||'application/octet-stream');res.setHeader('Content-Length',data.length);res.setHeader('Content-Disposition',`inline; filename="${String(f.originalName||f.name).replace(/["\\\r\n]/g,'_')}"`);return res.send(data)}catch(e){return res.status(404).json({error:e.message})}});
app.delete('/api/files/:id',async(req,res)=>{try{const f=await getEntity('files',req.params.id);if(!f)return res.json({deleted:false});await deleteBinaryFile(f);const deleted=await deleteEntity('files',req.params.id);if(deleted)await appendAudit('file_deleted',req.params.id,{},'warning');return res.json({deleted})}catch(e){return res.status(400).json({error:e.message})}});
const collections=['projects','assistants','memories','artifacts','tasks','notifications'];
for(const c of collections){const route=`/api/${c}`;app.get(route,async(_req,res)=>res.json({[c]:await listEntities(c)}));app.get(`${route}/:id`,async(req,res)=>{const e=await getEntity(c,req.params.id);if(!e)return res.status(404).json({error:`${c.slice(0,-1)} not found.`});return res.json({[c.slice(0,-1)]:e})});app.post(route,async(req,res)=>{try{const e=await upsertEntity(c,req.body);await appendAudit(`${c.slice(0,-1)}_created`,e.id,{},'info');return res.status(201).json({[c.slice(0,-1)]:e})}catch(e){return res.status(400).json({error:e.message})}});app.put(`${route}/:id`,async(req,res)=>{try{const e=await upsertEntity(c,{...req.body,id:req.params.id});await appendAudit(`${c.slice(0,-1)}_updated`,e.id,{},'info');return res.json({[c.slice(0,-1)]:e})}catch(e){return res.status(400).json({error:e.message})}});app.delete(`${route}/:id`,async(req,res)=>{const d=await deleteEntity(c,req.params.id);if(d)await appendAudit(`${c.slice(0,-1)}_deleted`,req.params.id,{},'warning');return res.json({deleted:d})})}
app.get('/api/audit',async(_req,res)=>res.json({audit:await listAudit()}));
const request=(a,model,messages,temperature,maxTokens)=>({providerId:a.providerId,model,apiKey:a.secret,baseUrl:a.baseUrl,messages,options:{temperature,maxTokens}});
async function targets(input){if(!Array.isArray(input)||!input.length||input.length>5)throw new Error('targets must contain 1 to 5 model targets.');const out=[];const cache=new Map();for(const t of input){if(!t?.accountId||!t?.model)throw new Error('Each target requires accountId and model.');let a=cache.get(t.accountId);if(!a){a=await getAccount(t.accountId);if(!a)throw new Error(`Account not found: ${t.accountId}`);cache.set(t.accountId,a)}out.push({...t,account:a})}return out}
async function persistTurn(conversationId,userMessage,responses,selectedTargets){if(!conversationId)return;const current=await getEntity('conversations',conversationId);if(!current)return;const turn={id:randomUUID(),role:'turn',userMessage,targets:selectedTargets.map(t=>({accountId:t.accountId,model:t.model})),responses,createdAt:new Date().toISOString()};await upsertEntity('conversations',{...current,messages:[...(current.messages||[]),turn],updatedAt:new Date().toISOString()})}
app.post('/api/chat',async(req,res)=>{const{accountId,model,messages,temperature,maxTokens,conversationId}=req.body||{};if(!accountId||!model||!Array.isArray(messages)||!messages.length)return res.status(400).json({error:'accountId, model and messages are required.'});try{const a=await getAccount(accountId);if(!a)return res.status(404).json({error:'Account not found.'});const result=await complete(request(a,model,messages,temperature,maxTokens));const response={id:randomUUID(),modelId:model,accountId,...result,createdAt:new Date().toISOString()};await persistTurn(conversationId,messages.at(-1)?.content||'', [response],[{accountId,model}]);return res.json(response)}catch(e){return res.status(502).json({error:e.message||'Provider request failed.'})}});
app.post('/api/chat/multi',async(req,res)=>{const{targets:raw,accountId,models,messages,conversationId}=req.body||{};const selected=Array.isArray(raw)&&raw.length?raw:(Array.isArray(models)?models.map(model=>({accountId,model})):[]);if(!selected.length||!Array.isArray(messages)||!messages.length)return res.status(400).json({error:'targets and messages are required.'});try{const resolved=await targets(selected);const results=await completeMany(resolved.map(t=>request(t.account,t.model,messages,undefined,undefined)));const enriched=results.map((r,i)=>({...r,id:r.id||randomUUID(),accountId:resolved[i].accountId,modelId:resolved[i].model,providerId:resolved[i].account.providerId,createdAt:new Date().toISOString()}));await persistTurn(conversationId,messages.at(-1)?.content||'',enriched,resolved);return res.json({id:randomUUID(),createdAt:new Date().toISOString(),results:enriched,conversationId})}catch(e){return res.status(502).json({error:e.message||'Multi-model request failed.'})}});
app.post('/api/chat/synthesize',async(req,res)=>{const{accountId,model,messages,sourceResponses,instruction,temperature,maxTokens,conversationId}=req.body||{};if(!accountId||!model||!Array.isArray(sourceResponses)||!sourceResponses.length)return res.status(400).json({error:'accountId, model and sourceResponses are required.'});const sourceText=sourceResponses.map((x,i)=>`MODEL ${i+1} (${x.modelId||x.model||'unknown'}):\n${x.content||''}`).join('\n\n');try{const a=await getAccount(accountId);if(!a)return res.status(404).json({error:'Account not found.'});const result=await complete(request(a,model,[...(Array.isArray(messages)?messages:[]),{role:'user',content:`Synthesize independent responses. Do not assume they are correct. Identify disagreements and uncertainty.\n\n${instruction||'Compare and synthesize.'}\n\n${sourceText}`}],temperature,maxTokens));const response={id:randomUUID(),modelId:model,accountId,...result,createdAt:new Date().toISOString()};await persistTurn(conversationId,'Synthesis',[response],[{accountId,model}]);return res.json(response)}catch(e){return res.status(502).json({error:e.message||'Synthesis failed.'})}});
const dist=path.resolve(__dirname,'../dist');app.use(express.static(dist));app.get('*',(_req,res)=>res.sendFile(path.join(dist,'index.html')));app.listen(port,'0.0.0.0',()=>console.log(`AI Nexus server listening on ${port}`));
