import React, { createContext, useContext, useEffect, useMemo, useState, ReactNode } from 'react';
import { AppTheme, NavigationSection, SupportedLocale, UIMode, ProviderAccount, AIModel, AuditLogEntry, AppNotification, ProviderId, ModelCapability } from '../types';
interface AppContextValue { locale:SupportedLocale;setLocale:(v:SupportedLocale)=>void;isRTL:boolean;theme:AppTheme;setTheme:(v:AppTheme)=>void;toggleTheme:()=>void;mode:UIMode;setMode:(v:UIMode)=>void;activeSection:NavigationSection;setActiveSection:(v:NavigationSection)=>void;accounts:ProviderAccount[];models:AIModel[];selectedModelIds:string[];toggleModelSelection:(id:string)=>void;refreshAccounts:()=>Promise<void>;refreshModels:(accountId?:string)=>Promise<void>;testAccount:(id:string)=>Promise<{ok:boolean;modelCount?:number;error?:string}>;addAccount:(input:{providerId:ProviderId;label:string;apiKey:string;baseUrl?:string})=>Promise<ProviderAccount>;removeAccount:(id:string)=>Promise<void>;isCommandPaletteOpen:boolean;setIsCommandPaletteOpen:(v:boolean)=>void;auditLogs:AuditLogEntry[];addAuditLog:(e:Omit<AuditLogEntry,'id'|'timestamp'>)=>void;notifications:AppNotification[];dismissNotification:(id:string)=>void;addNotification:(n:Omit<AppNotification,'id'|'createdAt'|'read'>)=>void; }
const AppContext=createContext<AppContextValue|null>(null); const API='/api'; const K={L:'ainexus_locale',T:'ainexus_theme',M:'ainexus_mode',S:'ainexus_selected_models'};
async function api(path:string,options?:RequestInit){const r=await fetch(`${API}${path}`,{headers:{'content-type':'application/json',...(options?.headers||{})},...options});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b?.error||`Request failed (${r.status})`);return b;}
const normalize=(m:any,accountId?:string):AIModel=>({id:m.id,providerId:m.providerId as ProviderId,name:m.name||m.id,description:m.description||'',contextWindow:m.contextWindow||m.inputTokenLimit||0,maxOutputTokens:m.maxOutputTokens||m.outputTokenLimit||0,capabilities:(m.capabilities||['chat']) as ModelCapability[],accountId});
export const AppProvider:React.FC<{children:ReactNode}>=({children})=>{
 const [locale,setLocaleState]=useState<SupportedLocale>(()=>localStorage.getItem(K.L)==='ar'?'ar':'en'); const [theme,setThemeState]=useState<AppTheme>(()=>localStorage.getItem(K.T)==='light'?'light':'dark'); const [mode,setModeState]=useState<UIMode>(()=>localStorage.getItem(K.M)==='advanced'?'advanced':'simple'); const [activeSection,setActiveSection]=useState<NavigationSection>('overview'); const [isCommandPaletteOpen,setIsCommandPaletteOpen]=useState(false); const [accounts,setAccounts]=useState<ProviderAccount[]>([]); const [models,setModels]=useState<AIModel[]>([]); const [selectedModelIds,setSelectedModelIds]=useState<string[]>(()=>{try{return JSON.parse(localStorage.getItem(K.S)||'[]')}catch{return[]}}); const [auditLogs,setAuditLogs]=useState<AuditLogEntry[]>([]); const [notifications,setNotifications]=useState<AppNotification[]>([]); const isRTL=locale==='ar';
 const refreshAccounts=async()=>{const b=await api('/accounts');setAccounts(b.accounts||[]);return b.accounts||[]};
 const refreshModels=async(accountId?:string)=>{const ids=accountId?[accountId]:accounts.map(a=>a.id);if(!ids.length){setModels([]);setSelectedModelIds([]);return;} const all:AIModel[]=[];for(const id of ids){try{const b=await api(`/accounts/${id}/models`);for(const m of b.models||[])all.push(normalize(m,id));}catch{}} setModels(all);setSelectedModelIds(prev=>prev.filter(id=>all.some(m=>m.id===id)));};
 const testAccount=async(id:string)=>{try{return await api(`/accounts/${id}/test`,{method:'POST',body:'{}'})}catch(e){return{ok:false,error:e instanceof Error?e.message:'Connection test failed.'}}};
 const addAccount=async(input:{providerId:ProviderId;label:string;apiKey:string;baseUrl?:string})=>{const b=await api('/accounts',{method:'POST',body:JSON.stringify(input)});const account=b.account as ProviderAccount;setAccounts(p=>[...p.filter(x=>x.id!==account.id),account]);await refreshModels(account.id);return account;};
 const removeAccount=async(id:string)=>{await api(`/accounts/${id}`,{method:'DELETE'});setAccounts(p=>p.filter(a=>a.id!==id));setModels(p=>p.filter(m=>m.accountId!==id));setSelectedModelIds(p=>p.filter(mid=>models.some(m=>m.id===mid&&m.accountId!==id)));};
 useEffect(()=>{refreshAccounts().then(()=>undefined).catch(()=>undefined)},[]); useEffect(()=>{if(accounts.length)refreshModels().catch(()=>undefined)},[accounts.length]);
 useEffect(()=>{document.documentElement.lang=locale;document.documentElement.dir=isRTL?'rtl':'ltr';localStorage.setItem(K.L,locale)},[locale,isRTL]); useEffect(()=>{document.documentElement.classList.toggle('dark',theme==='dark');localStorage.setItem(K.T,theme)},[theme]);useEffect(()=>localStorage.setItem(K.M,mode),[mode]);useEffect(()=>localStorage.setItem(K.S,JSON.stringify(selectedModelIds)),[selectedModelIds]);
 useEffect(()=>{const h=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setIsCommandPaletteOpen(v=>!v)}};window.addEventListener('keydown',h);return()=>window.removeEventListener('keydown',h)},[]);
 const toggleModelSelection=(id:string)=>setSelectedModelIds(p=>p.includes(id)?(p.length===1?p:p.filter(x=>x!==id)):[...p,id]); const addAuditLog=(e:Omit<AuditLogEntry,'id'|'timestamp'>)=>setAuditLogs(p=>[{...e,id:crypto.randomUUID(),timestamp:new Date().toISOString()},...p]);const dismissNotification=(id:string)=>setNotifications(p=>p.filter(n=>n.id!==id));const addNotification=(n:Omit<AppNotification,'id'|'createdAt'|'read'>)=>setNotifications(p=>[{...n,id:crypto.randomUUID(),createdAt:new Date().toISOString(),read:false},...p]);
 const value=useMemo(()=>({locale,setLocale:(v:SupportedLocale)=>setLocaleState(v),isRTL,theme,setTheme:(v:AppTheme)=>setThemeState(v),toggleTheme:()=>setThemeState(v=>v==='dark'?'light':'dark'),mode,setMode:(v:UIMode)=>setModeState(v),activeSection,setActiveSection,accounts,models,selectedModelIds,toggleModelSelection,refreshAccounts,refreshModels,testAccount,addAccount,removeAccount,isCommandPaletteOpen,setIsCommandPaletteOpen,auditLogs,addAuditLog,notifications,dismissNotification,addNotification}),[locale,isRTL,theme,mode,activeSection,accounts,models,selectedModelIds,isCommandPaletteOpen,auditLogs,notifications]);return <AppContext.Provider value={value}>{children}</AppContext.Provider>;
};
export function useApp():AppContextValue{const c=useContext(AppContext);if(!c)throw new Error('useApp must be used within an AppProvider');return c;}
